-- Siraat: Candidate Society reference list seed
-- Source: RDA candidate universe (77 records) + CDA candidate universe (69 records)
-- Per spec Section 3: these are CANDIDATE records, not verified societies.
-- No deduplication performed — near-duplicate names (e.g. "Bahria Town Phase-VIII"
-- appearing under both RDA and CDA, "Multi Gardens" vs "Multi Gardens Phase-I/II")
-- are preserved as-is, to be reconciled by the operator during real research,
-- not assumed identical by the system.
--
-- City defaults: RDA entries default to 'Rawalpindi', CDA entries default to
-- 'Islamabad' — these are starting defaults only; correct to Taxila/Wah Cantt
-- etc. as actual research confirms jurisdiction per Section 2's warning
-- ("Do not assume the regulator from the commercial name").
--
-- Run with: docker cp then psql -f (NEVER pipe through PowerShell — see
-- CLAUDE.md's documented encoding gotcha).
--
-- Prerequisite: the candidate_societies table must exist first (Step 1 —
-- Claude Code creates the CandidateSociety entity and TypeORM synchronizes it).

SET search_path = property_intelligence;

INSERT INTO candidate_societies (id, name, regulator, city, status, record_type) VALUES
-- ─── RDA Candidate Universe (77) ─────────────────────────────────────────────
(gen_random_uuid(), 'Al Haram City Phase 1 Part 1', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Kingdom Valley', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Forest Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Tariq Sharif Smart City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Prism Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'OGDC Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Lake Vista Residencia', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'T & T Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Faisal Hills-II', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Al-Khan Enclave', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Taj Residencia', 'RDA', 'Rawalpindi', 'ONBOARDED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-VIII', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Marble Arch Enclave', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Utility Cooperative Employees Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Commoners Sky Garden', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Faisal Margalla City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Faisal Hills', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'New City Housing Scheme (Phase-II)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rawalpindi Railway Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Shifa Cooperative Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rail View Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Judicial Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Fizaia Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Doctors Town Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'PARC Cooperative Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Municipal Corporation Cooperative Housing Scheme (Sector A&B)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Golden Jubilee Cooperative Housing', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Paradise', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Eastridge Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Safari Villas-II', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Army Welfare Housing Scheme (Defense-I)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rabia Bungalows', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town (Phase-I, II & III Partially)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Safari Enclave-II (Land Sub-Division)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bostan Avenue Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Safari Villas-I', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Sanober City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Clifton Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Revenue Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Kehkashan Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Abad Cooperative Housing Society (Gulshan-e-Abad)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Garden Villas', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-VIII', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'CBR Town Phase-II', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Kohsar View Housing Project', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gulshan-e-Fatima', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Foreign Office Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Up-Country Enclosure', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'University Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Tarnol Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Shalimar Town', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Khudadad City including Airport Enclave', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Pakistan Atomic Energy Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Silver City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Qurtaba City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Shahbaz Villas (Land Sub-Division)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'French Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Kohistan Enclave', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Multi Gardens', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Golf City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Dream Valley Housing Scheme', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rabia Residency', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Banker City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Al-Haram City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Pakistan Govt. Employees Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Safari Valley', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'PIA Officers Cooperative Housing Society', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'PECHS (Block K, K-Ext, M)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Faisal Town (Rev & Extension)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Capital Smart City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Taj Residencia (Extension)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Elite Reverie Housing (Eighteen)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gandhara City (Revised & Extension)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Airport Green Garden (Revised & Extension)', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Top City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rehbar Colony', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Mumtaz City', 'RDA', 'Rawalpindi', 'NOT_STARTED', 'FACT'),

-- ─── CDA Candidate Universe (69) ─────────────────────────────────────────────
(gen_random_uuid(), 'AGOCHS, Phase-I', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'AGOCHS, Phase-II', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Al-Hamra Avenue', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Al-Hamra Hills Agro Farming Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Al-Makkah City', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Anza Zephyr Dale Agro Farms', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Army Welfare Trust', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Enclave Phase-I', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Enclave-II, Agro Farming Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Enclave-II, Phase-II', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Garden City', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-III-E-IV', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-VII-E', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-VII', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Bahria Town Phase-II, III, V & VI', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Cabinet Division Employees Co-operative Housing Society', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Capital Enclave', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'CBR Town', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Engineers Co-operative', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Engineers Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Faisal Residentia Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Federal Government Employees Housing Foundation', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Federation of Employees', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'FIA Park Enclave', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Grace Valley', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gulberg Greens Farm Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gulberg Residencia', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gulshan-e-Rabia', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Gulshan-e-Sehat', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Icon Garden', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Islamabad Gardens', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Islamabad Model Town', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Jeddah Town', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Jinnah Garden Phase-I', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Jinnah Garden Phase-I Extension', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Jinnah Garden Phase-II', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Jinnah Town', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Kashmir Gardens Farming Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Khayaban-e-Kashmir Phase-I', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Khayaban-e-Kashmir Phase-II', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Khayaban-e-Kashmir Extension', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Margalla View Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Margalla View Housing Scheme Extension', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Ministry of Interior Employees Co-operative Housing Society', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Multi Gardens Phase-I', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Multi Gardens Phase-II', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'National Assembly Employees Cooperative Housing Society', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'National Cooperative Housing Society & New Islamabad Enclave', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'National Police Foundation', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Naval Anchorage', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'New Islamabad Garden', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'OPF Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Pakistan Medical Cooperative Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Pakistan Navy Farms', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Paradise City', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Park View City', 'CDA', 'Islamabad', 'ONBOARDED', 'FACT'),
(gen_random_uuid(), 'Parliamentarians Enclave', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Rahman Enclave Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'River Garden', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Roshan Pakistan Corporation Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Senate Avenue', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Services Co-operative Housing Society', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Soan Garden Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Supreme Court Employees Housing Scheme', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'T&T Employees Cooperative Housing Society', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Tele Gardens', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Tele Town', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'WWF Labor Colony', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT'),
(gen_random_uuid(), 'Zaraj Housing', 'CDA', 'Islamabad', 'NOT_STARTED', 'FACT')

ON CONFLICT DO NOTHING;

-- Sanity check after running:
-- SELECT regulator, COUNT(*) FROM candidate_societies GROUP BY regulator;
-- Expect: RDA = 77, CDA = 69 (146 total)
